# Generated by Django 4.0.2 on 2022-03-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('venue', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=10)),
                ('weblink', models.CharField(max_length=100)),
            ],
        ),
    ]
