# Generated by Django 4.0.2 on 2022-03-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='decs',
            field=models.TextField(null=True),
        ),
    ]
