# Generated by Django 4.0.2 on 2022-03-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.IntegerField(),
        ),
    ]
