# Generated by Django 4.0.2 on 2022-03-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_event_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(max_length=2),
        ),
    ]
