# Generated by Django 4.0.2 on 2022-03-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_event_day_alter_event_month_alter_event_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
