# Generated by Django 4.0.2 on 2022-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
