# Generated by Django 4.0.2 on 2022-03-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
