# Generated by Django 4.0.2 on 2022-03-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_comment_commentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_code',
            field=models.CharField(default='code', max_length=4),
            preserve_default=False,
        ),
    ]
