# Generated by Django 4.0.2 on 2022-03-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_event_admin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='decs',
            field=models.CharField(max_length=500),
        ),
    ]
