# Generated by Django 4.0.2 on 2022-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_event_decs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='admin_code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
